
services:
  api:
    build: .
    image: dm-api:v1
    container_name: dm-api
    environment:
      - PORT=3000
      - PGHOST=postgres
      - PGUSER=apiuser
      - PGPASSWORD=apipassword
      - PGDATABASE=apidb
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=apiuser
      - POSTGRES_PASSWORD=apipassword
      - POSTGRES_DB=apidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
