stages:
  - lint
  - test
  - build

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

lint:
  stage: lint
  image: node:18-alpine
  script:
    - cd api
    - npm ci
    - npx eslint . || echo "Lint warnings only"
  only:
  - branches
  - merge_requests
    
build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - cd api
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
  - branches
  - merge_requests

test:
  stage: test
  image: node:18-alpine
  services:
    - name: postgres:16-alpine
      alias: postgres
  variables:
    NODE_ENV: test
    PGUSER: app
    PGPASSWORD: app
    PGDATABASE: dernier_metro
    PGHOST: postgres
    PGPORT: 5432
  script:
    - cd api
    - npm ci
    - npm test
  only:
  - branches
  - merge_requests


